### PR TITLE
Fixed typos in GeneratedIRReference.rst

### PR DESCRIPTION
**Pull request by zTehRyaN**

### CODE REVIEW

**Comment by aleclearmind** [comment]
Marking this draft. Undraft it once you were able to reproduce the commands in the document.

**Comment by aleclearmind** [comment]
Great!

A couple of things though:

* "rst: `--no-link` no more needed" -> "GeneratedIRReference.rst: `--no-link` no more needed"
* "readme: General fixes" -> "GeneratedIRReference.rst: general fixes"
* Use your rev.ng e-mail for all of your commits
* Rebase

**Comment by aleclearmind** [comment]
Why did you close this PR? I've lost it and never merged it.
Maybe you accidentally delete your branch?

**Comment by zTehRyaN** [comment]
Oh yes, I renamed the branch into `feature/readme` (which closed this PR) but I forgot to issue a new PR with the adjustments you proposed.
Do you want me to make the proper adjustments and issue a new proper PR?

**Comment by aleclearmind** [comment]
No, I think @andrealinux1 offered to revive the PR with an extra change.
I just wanted to understand what happened and if I missed.

**Pull request closed without merging**
