### PR TITLE
Convert revng-lift to a library

### PR DESCRIPTION
**Pull request by FredyR4zox**
Hello,

I've modified revng-lift to be used as a library. The files inside tools/revng-lift/ were placed in include/ and lib/ directories. Only the Main.cpp stayed. The #include directives were modified (added path to files) to reflect the changes of the files to the include/ directory.

Unfortunately I can't compile it so be advised that it might fail building.

Thank you

### CODE REVIEW

**Comment by aleclearmind** [comment]
Mmmh, why can't you compile it? I can help with that.
It's the PR author's responsibility to ensure PR properly compile and pass tests.

**Comment by FredyR4zox** [comment]
It gives me this error:

```bash
-- Looking for include file valgrind/callgrind.h
-- Looking for include file valgrind/callgrind.h - found
CMake Error at CMakeLists.txt:207 (include):
  include could not find load file:

    /usr/local/share/revng/qa/cmake/revng-qa.cmake


-- Found Boost: /usr/lib64/cmake/Boost-1.75.0/BoostConfig.cmake (found version "1.75.0") found components: unit_test_framework 
CMake Error at tests/analysis/AnalysisTests.cmake:65 (register_derived_artifact):
  Unknown CMake command "register_derived_artifact".
Call Stack (most recent call first):
  tests/Tests.cmake:9 (include)
  CMakeLists.txt:209 (include)


-- Configuring incomplete, errors occurred!
See also "/home/fredyr4zox/Builds/Thesis/Depedencies/eh/revng/build/CMakeFiles/CMakeOutput.log".
See also "/home/fredyr4zox/Builds/Thesis/Depedencies/eh/revng/build/CMakeFiles/CMakeError.log".
```

All the help is appreciated.

**Comment by aleclearmind** [comment]
It seems like you're building outside of orchestra.
Are you following [the orchestra instructions](https://github.com/revng/orchestra)?

**Comment by FredyR4zox** [comment]
Hi,

I've managed to compile it using orchestra. Thank you @aleclearmind :)
It compiled and passed all the tests.

**Comment by aleclearmind** [comment]
Thanks, looks quite good and relatively simple. Give me some time to try it out and then I think it can go in.

**Comment by aleclearmind** [comment]
This PR has been superseded by #55. Thanks!

**Pull request closed without merging**
