### PR TITLE
`TupleTree`: `visitReferences` with non-const visitors

### PR DESCRIPTION
**Pull request by pfez**

### CODE REVIEW

**Comment by aleclearmind** [comment]
I trust you on this one, but is more of this coming?
Shall we have a PR for the caching/uncaching of TTRs?

**Comment by pfez** [comment]
> I trust you on this one, but is more of this coming? Shall we have a PR for the caching/uncaching of TTRs?

This is unrelated with caching/uncaching, so if you don't have anything against it, I'd keep them separated.

The caching/uncaching needs a little more love, so I was planning to do a separate PR. I wouldn't block this from getting merged to wait for caching/uncaching. But your call.

**Comment by aleclearmind** [comment]
If no one is revng/revng-c is using this, I'd attach this PR to the first PR doing that.

**Comment by pfez** [comment]
Makes sense. I'll make a single one with the cache/uncache thing then.

**Comment by pfez** [comment]
What about switching it to "wip"? I'll update it with the rest of the commits later on and re-request a review.

**Comment by aleclearmind** [comment]
The branch name is not appropriate, I think.
In any case, more than `wip` you can draft it.

**Comment by pfez** [comment]
I'm gonna close this. I hoped github would let me change the source branch of the PR but apparently it does not. I'll open a new one with the correct branch.

**Pull request closed without merging**
