### PR TITLE
`revng daemon` improvements

### PR DESCRIPTION
**Pull request by mrjackv**

### CODE REVIEW

**Comment by aleclearmind** [comment]
Do you expect this to be all you'll need for the cloud stuff or you want me to leave it open in case more stuff needs to go in?

**Comment by mrjackv** [comment]
I'd keep it open until the `revng-distributable-revamp` is merged, this is subsequent and will only make sense then.
In terms of roadmap this is all that will be needed, but I want to be cautious.

**Comment by aleclearmind** [comment]
ACK, marking it as draft. Undraft it when ready to be merged.

**Comment by mrjackv** [comment]
Closing this as it has been superseded by #254

**Pull request closed without merging**
