### PR TITLE
Add pointer size to the model's information

### PR DESCRIPTION
**Pull request by AlviseDeFaveri**
Add a function that, given the architecture of the binary analyzed, returns the byte size that registers holding pointers have in that architecture.

### CODE REVIEW

**Comment by pfez** [comment]
@aleclearmind I just wanted you to know that this PR is blocking `revng-c` from starting to emit `model::Type`s from DLA.

**Comment by pfez** [comment]
@AlviseDeFaveri this PR should now merge into `develop` not into `feature/dynamic-functions` anymore. I just updated the PR target branch, but you still need to rebase it, since now it seems that there are some spurious commits.

**Comment by AlviseDeFaveri** [comment]
@pfez should be fixed now, ready to merge

**Comment by aleclearmind** [comment]
Merged @Cvelth's version of this in 52f7432.

**Comment by pfez** [comment]
Thanks. @AlviseDeFaveri can you update your `revng-c` merge request if necessary to work with the merged version?

**Comment by AlviseDeFaveri** [comment]
> Thanks. @AlviseDeFaveri can you update your `revng-c` merge request if necessary to work with the merged version?

done

**Pull request closed without merging**
